version: '3'

services:
  chatservice:
    build: .
    container_name: chatservice_app
    volumes:
      - .:/go/src
    ports:
      - "8081:8080"
      - "50052:50051"
    networks:
      - fcfx

  mysql:
    image: mysql:8
    container_name: mysql-chatgpt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_gpt
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306  
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - fcfx

networks:
  fcfx:
    external: true
